### ISSUE TITLE
Running the code without Jupyter

### ISSUE THREAD

**Issue by Saasbert** [Bunsly/JobSpy#164]
I'm trying to run the sample code without Jupyter (i can do it with Jupyter) but i'm running into errors.

Is there any instructions / insights on how to run the code by iteself ?
(i'm new to python, so very possible its just something i dont understand about the environment)

errors i'm getting :

Traceback (most recent call last):
  File "\examples\JobSpy_AllSites.py", line 4, in <module>
    jobs: pd.DataFrame = scrape_jobs(
  File "\jobspy\__init__.py", line 118, in scrape_jobs
    site_value, scraped_data = future.result()
  File "_base.py", line 451, in result
    return self.__get_result()
  File "_base.py", line 403, in __get_result
    raise self._exception
  File "thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "\jobspy\__init__.py", line 109, in worker
    site_val, scraped_info = scrape_site(site)
  File "\jobspy\__init__.py", line 99, in scrape_site
    scraper = scraper_class(proxy=proxy)
TypeError: IndeedScraper.__init__() got an unexpected keyword argument 'proxy'

**Comment by cullenwatson** [comment]
id just use the example in the readme. apologies need to update the examples folder.
